name: Deploy Data Processing API

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      